### ISSUE TITLE
Suggestion: replace Oracle with just a function

### ISSUE THREAD

**Issue by zsunberg** [jonathan-laurent/AlphaZero.jl#10]
If `Oracle` has only one function, `evaluate`, why not just replace it with a `Function`? That way, you'll have to maintain and document less code, potential users will not have to understand Julian object-oriented programming to implement a new heuristic, and you will not have to explain what an `Oracle` is. (I have learned this lesson over and over again trying to write similar code for others to use :smiley: ).

**Comment by zsunberg** [comment]
You can still keep your old rollout oracle like this:

```julia
struct RolloutOracle <: Function end

function (o::RolloutOracle{Game})(board) where Game
  state = Game(board)
  n = length(GI.available_actions(state))
  P = ones(n) ./ n
  V = rollout!(state, board)
  return P, V
end
```

or something

**Comment by jonathan-laurent** [comment]
I think this is sound advice in general, although in this case `Oracle` has two functions: `evaluate` and `evaluate_batch` (the latter having a default implementation).

Thanks for the feedback. 😃

**Comment by zsunberg** [comment]
Ah, I see. That does make it slightly less obvious what the most clear way is.

Just to note, it is still possible to have it be a `Function` since you can have
```julia
function evaluate_batch(f::Function, boards)
  return [f(b) for b in boards]
end
```
for the default and you can implement a special version of `evaluate_batch(::SpecialOracle, boards)` even if `SpecialOracle` is a `Function`.

Regardless of whether you keep the `Oracle` abstract type, supporting plain, non `Oracle` functions somehow will lower the barrier to entry. People will want to try toy examples and specifying
```julia
(m, s) -> -norm(s-goal_location(m))
```
is way easier and requires less cognitive load than
```julia
struct MyOracle <: Oracle{MyMDP}
    m::MyMDP
end

AlphaZero.evaluate(o::MyOracle, s) = -norm(s-goal_location(o.m))

MyOracle(m)
```
ESPECIALLY if they are new to Julia. (this all assumes that they are using some MDP where there is a goal location, and I don't think it matches up exactly with your current `Game(board)` paradigm, which I don't understand fully atm)

Allowing the use of normal `Functions` here makes the simple things easy and can scale to more complicated cases, while having an `Oracle` type forces the user to immediately jump to the more complicated scenario. I don't mean to barge in and criticize your code too much - just want to share my experience :smiley:

**Comment by jonathan-laurent** [comment]
No worry, I really appreciate critical feedback and I think you are making good points!

I fully agree about the interest of supporting plain functions as oracles. To be honest, the main reason I haven't implemented it yet was because I have been mostly focused on neural network oracles, for which the "object oriented" approach is somewhat idiomatic. But this is definitely something I should fix.

Also, for the anecdote, I originally used the functor notation for `Network.forward` to enable using neural networks like functions. However, I changed my mind after I was hit by https://github.com/JuliaLang/julia/issues/14919. I should probably revisit this.
