### ISSUE TITLE
Does it make sense to attempt to apply AlphaZero to "Agricola"

### ISSUE THREAD

**Issue by ihph** [jonathan-laurent/AlphaZero.jl#100]
I am attempting to create a Game Interface for Agricola. This is a different class of game to the ones that are usually used in reinforcement learning. Some key properties are:
- 1 to 4 players => each of whom is a farmer making trade-off decisions on what actions to take at each round (breed animals or grow food or buy an oven or increase family size or collect resources etc)
- each player starts with 2 actions during each round, but a possible action is to increase family size, which allows that player an extra action in subsequent rounds (at the cost of having to feed an extra person). Another possible action (in multiplayer games) is to become the starting player in the next round (which has the advantage that no other player can 'steal' the action they were intending to take...)
- the game ends after 14 rounds
- at the end of certain rounds (4,7,9,11,13,14) there is a harvest and the family must be fed (using either wheat or animals) if a player cannot feed the family they accumulate penalty point that are subtracted from the final score 
- each player gets final a score that depends on how what they have achieved over the course of the game (family size + # of animals + wheat in fields + # of rooms in house + number of fields - penalties ....)

I feel like the closest example to start from is the grid-world MDP. I was aiming to start as simply as possible with the one player version of the game where the aim is simply to maximise the score after x  rounds (and mybe simplifying it further by removing the possibility of adding actions during the game). I feel like AlphaZero could learn this type of game (although i'm not sure it is zero-sum). I presume the 1-pIayer game has one (or more) exact solutions, with >1player it become much more interesting... I feel that it is possible to specify / vectorize the state of the game (once i've refreshed my Juila skills!) albeit with larger state matrix and action mask than the example games. I feel like the first challenge will be specifying the fact that different actions become available as the rounds progress, and that harvest must be calculated at irregular intervals.

*In view of all this I would like to be sure that alphazero and MCTS can sensibly be applied to this type of game...*

(Any ideas on solving the irregular turns / harvests + change of player order as the game progresses... are welcome)

Thanks !

For anyone interested:
- [solo playthrough video](https://boardgamegeek.com/video/334600/agricola-family-edition/solo-playthrough-agricola-family-edition) - gives an idea of how the game works
- [blog post on Board Game Geek](https://boardgamegeek.com/blogpost/4135/agriconomics) - very detailed blog post on why this game is interesting & 'economically realistic'

**Comment by jonathan-laurent** [comment]
Thanks for your interest in AlphaZero.jl and sorry for the late reply!

This sounds like a very interesting game and it sounds like AlphaZero would be a good match to it.

The irregular turns are not a problem, since which player is the current implementation does not mandate alternating turns.

Regarding the variable number of actions, it may force you into using an awkward encoding but I don't see a major obstacle here. For example, if there can never be more than ten actions available, you may just have an action space of size ten and use masks. You may have to add some state information so specify which action number is associated with each action though.

The only thing that may be problematic is to handle the case of having more than two players. As I say in another issue, games with more than two players have fairly different game theoretic properties and it is no clear how AlphaZero can be applied in those cases.
