### ISSUE TITLE
Register package with General registry

### ISSUE THREAD

**Issue by ViralBShah** [jonathan-laurent/AlphaZero.jl#13]
It would be really nice if the package could be registered in the General registry. That would make it extremely easy for folks to try out and build on top of.

**Comment by jonathan-laurent** [comment]
I agree I should register AlphaZero.jl.

Actually, the main thing that has been holding me back is that I am still unsure about the best way to package it.
Currently, AlphaZero.jl contains several independent parts:

- A modular implementation of AlphaZero with many reusable components.
- A library of common network architectures for both Flux and Knet.
- A command-line interface along with many helper scripts for tuning, plotting and profiling.
- A library of examples (for the moment, it only features tictactoe and connect-four).

There are several problems with releasing all these components in a single package:

- It forces many unnecessary dependencies onto people who just want to build on the core algorithm.
- In particular, as you noticed, I have to list both Knet and Flux as dependencies in order to provide support for both.
- In general, I suspect that releasing AlphaZero.jl as a monolithic package might discourage future contributions.

One solution would be to split AlphaZero.jl into several Julia packages. However, this would require splitting the project into multiple git repositories, which creates many problems of its own, as demonstrated by the recent example of CUDA.jl going back on this choice.

**Comment by jonathan-laurent** [comment]
**Edit:** while writing this answer, I found an issue that pretty much addresses the problem I was mentioning: https://github.com/JuliaLang/Pkg.jl/issues/1251. I am very happy to see Pkg.jl moving in this direction.

I guess the other reason I have been delaying registering AlphaZero.jl is that it is still evolving very fast.

**Comment by ViralBShah** [comment]
I think it is fine to register as is (mainly to make it easy for people to try out). Eventually, it can always be split up into more packages. But yes, I face the same question with Circuitscape.jl  - which has similar UI components. For now we ship the whole thing as is in one package, and the users like the simplicity.

Some people are doing their own registries so that they can have a collection of packages, and then users add that registry to their Julia install to use those packages. Something to consider perhaps in the future. The thing with all of this is the increased maintenance effort.

**Comment by jonathan-laurent** [comment]
Thanks for the feedback!
I will be registering the package after the next release.
