### ISSUE TITLE
GPU vs  CPU

### ISSUE THREAD

**Issue by DmitriMedved** [jonathan-laurent/AlphaZero.jl#144]
Is there anyone who made experiments with Alphazero.jl: how faster the computer with GPU solves the game than CPU only?

**Comment by DmitriMedved** [comment]
Which hyperparameters we need to change to solve the game by CPU in a proper time?

**Comment by idevcde** [comment]
I would definitely follow above suggestion about going with a GPU (you could hardly get a better advice than from the author of the package). I attempted to train this model on CPUs. For details pls see [Questions on parallelization](https://github.com/jonathan-laurent/AlphaZero.jl/issues/71). It was my very first contact with Julia so I guess not everything there is perfect but in general it should not be that bad.

Based on my experience, the speed of the first part of the training (self play / learning) is acceptable on the latest CPUs (it takes about 1 hour) with the use of Distributed (all cores utilized) and based on my experience with NVIDIA V100 the timing is pretty similar. However, what I noticed was pretty low GPU utilization, slightly exceeding 30%. Please take this GPU info with a grin of salt, because my Julia GPU setup was quite preliminary and I have not been repeating those tests. AFAIK, the problem with CPU training relates to the next three stages that are running only on 1 core and are extremally slow. Again, AFAIK, those three stages may not be obligatory (or are they?) so if you omit them you may get similar CPU / GPU timings. I should probably add that the CPU computer I used, in terms of the cost probably exceeded the cost of the GPU, so I believe this is an important information. 

What is the machine are you planning to use @DmitriMedved? Are you maybe in the cloud? How would you approach the subject? Would you have any comments or suggestions?

**Comment by DmitriMedved** [comment]
idevcde, I'm not an expert in julia as well. I tried to train on cpu 2,1GHz, 8 cores, with no gpu and it was extremely slow. Maybe AlphaZero.jl doesn't use all cores by default?

**Comment by DmitriMedved** [comment]
Num_filters is 128. Maybe it's too large

**Comment by idevcde** [comment]
@DmitriMedved, frankly I do not think its realistic on 8 cores. Even if you try to implement non allocating tricks like in SimpleChains.jl which I really do not know if is possible at all in case of AlphaZero.jl. I simply think that the model is too big for this kind of computing power. My point is that it might be potentially very useful to use CPUs in case of large models and cloud or cluster environments where significant number of CPU power is easily available.  Otherwise, I would rather strongly follow author's documentation and its part related to training on GPUs.

**Comment by idevcde** [comment]
Just came by this article: https://www.servethehome.com/more-cores-more-better-amd-arm-and-intel-server-cpus-in-2022-2023/. Not sure what your position and plans are, however, I still think that 8 cores is out of the question as for now. Maybe with the next CPUs generation/s and next AlphaZero releases. Looks like interesting time both on hardware and software side.
