### ISSUE TITLE
Sanity Checks

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#52]
Hey! I've nearly completed rigging up my game and am excited to begin running it. I had some quick questions that I wanted to run by you. Just some quick sanity checks to ensure my understanding of everything is correct as if I'm wrong these will likely break my training.

1) State Vectorization
1.a) Why in the examples is this always made to be from whites side?
1.b) When is state vectorization executed? Each turn or at the end of a game?
1.c) Is state vectorization done for both black and white?
1.d) What should be included in state vectorization?

2) Other connect-four example questions
2.a) Pretty sure I'm correct but to confirm update_status! and update_actions_mask! I've included that logic in my play! function is this fine? or is it required the logic for these be in their own functions?
2.b) In connect-four there's a function GI.clone I assume this is for something external specific to connect-four?

3) Other
3.a) What exactly is observation? Everything in state in the game env? Or is it everything in state vectorization?

Once again, really appreciate your help as well as other members of the community with their feedback. Thanks a ton for even making this in the first place it's amazing!

**Comment by jonathan-laurent** [comment]
I am happy to hear you are finding AlphaZero.jl useful!

To answer your questions:

- 1.a. Very good question. The network must always evaluate a board position from the perspective of the **current player**. Therefore, one way to encode the state would be to represent the board and also add a flag indicating who the current player is. In symmetric games where the rules are the same for both players, it is often easier not to have such a flag and flip colors if necessary so that the current player is always white (from the perspective of the network)
- 1.b. State vectorization is needed every time a state must be evaluated by the network. This happens many times per turn (about once per MCTS simulation and so 600 times per move in my connect-four benchmark)
- 1.c. See answers above.
- 1.d. The state vectorization is just an alternative representation of the state that is network-friendly (e.g. a tensor of floating point numbers). Most of the time, there is a one-to-one correspondence between states and valid factorized states (modulo the player symmetry mentioned in 1.a). It is possible in some cases to purposefully remove some info from the vectorized state but it may prevent the network to make good predictions
- 2.a. these functions are just internal implementation details for my connect-four implementation. AlphaZero does not care how `play!` is implemented as long as you respect the public GameInterface API.
- 2.b. The cloning operation is part of the game interface and required to implement for every game. MCTS relies on the ability to clone game states.
- 3.a. Where is the notion of observation mentioned in AlphaZero.jl? AlphaZero works for fully-observable environments, meaning that the notion of observation coincides with the notion of state (which is not the case in other reinforcement learning environments, including POMDPs)

PS: please do not hesitate to submit PRs with additional game tests or updates to the documentation if you find anything unclear or missing!

PPS: JuliaCon 2021 is happening right now and there will be a [talk](https://live.juliacon.org/talk/NLG9FQ) about AlphaZero.jl in about two hours. The video will be available later on youtube but don't hesitate to come and see the talk in live (registration to JuliaCon is free and only takes a couple of minutes).

**Comment by SheldonCurtiss** [comment]
> PS: please do not hesitate to submit PRs with additional game tests or updates to the documentation if you find anything unclear or missing!

You're a legend! Thanks these are really helpful! Glad to hear, I'm trying not to be a nuisance, Julia is completely new to me and most of my experience is with standard CNNs and RNNs, I've only recently gotten into reinforcement learning and actually made the switch to your project as speed was such a massive issue with 'MuZero', it also had a pretty brutal bottlenecks.

> * 3.a. Where is the notion of observation mentioned in AlphaZero.jl? AlphaZero works for fully-observable environments, meaning that the notion of observation coincides with the notion of state (which is not the case in other reinforcement learning environments, including POMDPs)

Sorry - I'm just trying to apply my existing knowledge to this, I'm not entirely sure I understand this answer? So this means that everything in state is effectively observable by the 'agents' or would be in the equivalent of being inside 'observation'?

> PPS: JuliaCon 2021 is happening right now and there will be a [talk](https://live.juliacon.org/talk/NLG9FQ) about AlphaZero.jl in about two hours. The video will be available later on youtube but don't hesitate to come and see the talk in live (registration to JuliaCon is free and only takes a couple of minutes).

Am registered, on the discord, and have the link open! Can't wait to see it!

**Comment by jonathan-laurent** [comment]
> > * 3.a. Where is the notion of observation mentioned in AlphaZero.jl? AlphaZero works for fully-observable environments, meaning that the notion of observation coincides with the notion of state (which is not the case in other reinforcement learning environments, including POMDPs)
> 
> Sorry - I'm just trying to apply my existing knowledge to this, I'm not entirely sure I understand this answer? So this means that everything in state is effectively observable by the 'agents' or would be in the equivalent of being inside 'observation'?

By definition, a state is an object that contains all the info 

The definition of a state is that it contains all the info necessary to simulate all possible scenarios forward. Therefore, an agent can always make optimal decisions given a state and does not need access to the history of previously encountered states, observations or actions.

Some environments are said to be fully-observable, in the sense that the agent has access to the full state of the environment after each action. This is the case in chess, Go, connect-four... In other settings though, only partial information about the current state is given to the agent at each step and this partial information is usually called "observation".

AlphaZero is designed to work on fully-observable environments. Therefore, the notions of state and observations are effectively the same.

**Comment by SheldonCurtiss** [comment]
Alright that helps!
I'm struggling with the state vectorization.
My data that is used in making decisions 'board' is data fed in from a csv file, this data is in a Matrix{Float64}. Though I don't think I need float64 and would be fine with float32?
There's also player scores, and if each player has 'jumped' or 'landed' as that effects future moves.

Looking at the example it appears this needs to be in Array{Float32, 3}???
I'm pretty sure from your other responses I need to include if each player has jumped or landed. I'm not entirely sure how to take my data and set it up for this?

Everything else is in place but I'm stuck on this... Do you have any examples of how you'd go about this?

**Comment by jonathan-laurent** [comment]
I cannot really answer this question without knowing more about your application.
A vectorized state should be something that can be fed to your neural network. If your data is of variable-length, you will not be able to use the SimpleNet and ResNet networks from the networks library and you may have to roll your own RNN architecture or something similar.

In my opinion, you should not focus on vectorization and rather think about what neural network architecture makes sense for your purpose. Then, how to vectorize will be obvious. :-)
