### ISSUE TITLE
Current status of Multi-threading MCTS Benchmarking?

### ISSUE THREAD

**Issue by SheldonCurtiss** [jonathan-laurent/AlphaZero.jl#56]
Hey - You previously mentioned you were working on this, any eta as to when you think this will be completed?

If not and if I was to attempt to do this myself do you have any pointers or suggestions as to how you would approach this?

**Comment by jonathan-laurent** [comment]
I imagine you are making a reference to my JuliaCon talk where I mentioned that multithreading overhead may harm AlphaZero.jl performances? Honestly, investigating this is not on the top of my priority list because I know some of these issues (such as the GC not dealing well with multiple heavily allocating threads) are being worked on right now by the Julia devs.
