### ISSUE TITLE
How to use multiple GPUs on a single node

### ISSUE THREAD

**Issue by bochen0909** [jonathan-laurent/AlphaZero.jl#69]
I am new to julia.  

I ran the command  (on branch master and with julia version 1.6.2)

> julia --project -e 'using AlphaZero; Scripts.train("connect-four")'

on a single node with 4 gpus, but found only the first one is used. 

How could I use all the gpus?

Thanks.

**Comment by jonathan-laurent** [comment]
Good question.
I never tried to use multiple GPUs per node myself but it should be possible.
Basically, what you would have to do is to spawn multiple Julia processes per machine as AlphaZero.jl uses one GPU per inference server and spawns one inference server per process. You might have to add a one or two lines of code to make sure that every process is using a different GPU though.

If you manage to make it work, don't hesitate to report back so that I can add your solution to the documentation and make it easier for the next person!

**Comment by bochen0909** [comment]
Here is a way I tired for those who are interested in. 

First make a load file, e.g. load.jl
```
using CUDA, Distributed
ngpu=length(devices())
addprocs(ngpu-1; exeflags="--project")

@everywhere using CUDA

# assign devices
asyncmap((zip(workers(), collect(devices())[2:ngpu]))) do (p, d)
    remotecall_wait(p) do
        @info "Worker $p uses $d"
        device!(d)
    end
end
```

Then run 
```
julia --project -L load.jl  -e 'using AlphaZero; Scripts.train("connect-four")'
```
In case of 4 GPUs (0,1,2,3) , it spawns 3 worker processes where GPU 1,2,3 are used for each. 
Self-play step is distributed with the 3 worker processes. Other steps (learning, evaluation, benchmark) run in main process with GPU 0,
