### ISSUE TITLE
Cloud computing

### ISSUE THREAD

**Issue by casper2002casper** [jonathan-laurent/AlphaZero.jl#80]
As my pc is not very performant, I was evaluating options for cloud computing. I found the following options and wonder if anyone has experience with using them for AlphaZero.jl:

- JuliaHub, has nicely integrated services, however documentation only shows (virtual)CPU support, so I'm wondering how it will perform on  DNN training, and how affordable it is to use for some decent training.
- Google cloud computing has a free $300 budget trial and offers high-performance computing resources, seems like using Julia on there should be doable.
- Google colab is free to use and allows using both GPU's and TPU's, however your session can get interrupted after a while.

Edit: Found this article on using AZ.jl with Google colab, https://towardsdatascience.com/training-alphazero-in-google-colab-cc2f1d6bd0ba . Seems quite nice to use and free, so will go with that.

**Comment by jonathan-laurent** [comment]
I wasn't aware of this medium article. Thanks for mentioning it to me!
(And thanks to the author of this medium article)

**Comment by casper2002casper** [comment]
It might be interesting to add an updated notebook to the documentation to get people started

**Comment by casper2002casper** [comment]
I did some testing, and it seems that performance isn't as described in the article, in the article a single iteration of connect-four takes less than an hour while in my testing it takes around 9 hours. Either google decreased computing power massively or it's not efficiently using the gpu, is there a way to test that?

**Comment by jonathan-laurent** [comment]
9h seems awfully long for a single iteration indeed. I am not familiar with Colab but can you have access to your CPU/GPU utilization stats?

**Comment by idevcde** [comment]
Hi,

>JuliaHub, has nicely integrated services, however documentation only shows (virtual)CPU support, so I'm wondering how it will perform on DNN training, and how affordable it is to use for some decent training.

I suggest you take a look at those videos: https://youtu.be/80jBqGqKW6c and https://youtu.be/JVUJ5Oohuhs. There is info about setup as well as affordability.

>Google cloud computing has a free $300 budget trial and offers high-performance computing resources, seems like using Julia on there should be doable.

In general (as far as I am recalling) during the trial there is a default limit to max 8 CPU and 32 or 64 GB of RAM. No GPU is allowed by default during the trial. As far as I understand, currently to run AZ.jl on CPUs this number of cores is not enough and the amount of RAM is rather also not enough. You may try to contact Google with additional information on the type of calculations you are planning to do. As far as I know, there is a high chance that the limit could be increased and GPU support will be provided. However, even so, based on my experience, running AZ.jl on CPUs might be the most cost effective as the first part of the training takes similar time to perform on about 60 cores as on one v100.

>Google colab is free to use and allows using both GPU's and TPU's, however your session can get interrupted after a while.

As far as I know, the type of GPU that is provided to you is more or less random. There is a chance that you will be provided with V100, however, on most of the occasions you will be provided with much less performant hardware like K80. You may research Colab Pro and Colab Pro+ that should give you better GPU access, however, I would advise to read more about those services because as far as I am recalling they were not available in every part of the world and there were also some constraints associated.
